### ISSUE TITLE
Block Deletion Hermitpack 1.1.0 MC 1.10.2

### ISSUE THREAD

**Issue by chrismilson** [Chisel-Team/Chisel#287]
When using the iChisel, if have several stacks of a block in my inventory and I select one with less than a full stack then when I "Chisel All" all of the full stacks are changed to have the same number of items as the non full stack. e.g. I have 3 full stacks of Factory Blocks and one half stack. When selecting the half stack, choosing the block to change to and pressing "Chisel All" I am left with four half stacks of the new block.

**Comment by TehNut** [comment]
#262

**Comment by chrismilson** [comment]
Not the same problem.

**Comment by chrismilson** [comment]
This is not the same problem; not sure what else you could mean.

**Comment by tterrag1098** [comment]
It is the same problem. Stop reporting modpack issues to mods.

**Comment by chrismilson** [comment]
No it isnt, I already implemented the fix for #262

**Comment by tterrag1098** [comment]
You still failed to provide version numbers, and my above statement still stands.

**Comment by chrismilson** [comment]
Sure. Have a nice day.

**Comment by tterrag1098** [comment]
I reopened it for a reason.

**Comment by chrismilson** [comment]
Chisel version 0.0.7.3

**Comment by Builderb0y** [comment]
Also lovely is that it works the other way around too; selecting the full stack for chisel-all'ing sets all the other stacks to a quantity of 64, so it can dupe items just as easily as delete them.

**Comment by Drullkus** [comment]
I'm not able to reproduce this in the latest. Closing unless reported occurring on latest

**Comment by Builderb0y** [comment]
Can confirm this is fixed in version 0.0.9.11 for MC 1.11.2, however it's still broken in 0.0.8.13 for MC 1.10.2.

**Comment by SDUBZ** [comment]
this bug is back in chisel -1.11.2-0.0.11.16
Forge:1.11.2-2315
ctm:1.11.2-01.1.6
![2017-06-24_21 32 59](https://user-images.githubusercontent.com/14084377/27508348-10917878-5926-11e7-90ef-890099ce6e70.png)

![2017-06-24_21 33 16](https://user-images.githubusercontent.com/14084377/27508349-14523bfa-5926-11e7-9496-b8f5e92270b1.png)

![2017-06-24_21 33 22](https://user-images.githubusercontent.com/14084377/27508350-17bd1a58-5926-11e7-9011-5c816faede4f.png)
