### ISSUE TITLE
[1.7.10] ThermalExpansion Cache Dupe Chisel

### ISSUE THREAD

**Issue by ghost** [Chisel-Team/Chisel#34]
https://youtu.be/xUGbq7IuMDw

**Comment by tterrag1098** [comment]
This was definitely fixed. What version are you on?

**Comment by ghost** [comment]
I do not use this version, I created a notification of a possible dupe.
I use Chisel2 and created a ticket there: https://github.com/Chisel-2/Chisel-2/issues/418

**Comment by tterrag1098** [comment]
It was fixed there too. Again, what version?

**Comment by ghost** [comment]
Chisel2-2.5.0.43

**Comment by MySt1k** [comment]
It's horrible. The problem is not completely resolved. It is enough to use the selected version without this check on a client and DUP will be possible.
