### ISSUE TITLE
DEV-MC1.11.2-0.0.8.5 world gen stone generating as Panel instead of Raw

### ISSUE THREAD

**Issue by Rosethorns** [Chisel-Team/Chisel#350]
The world gen stone marble, limestone and basalt is generating as the panel variant rather than raw.

**Comment by Drullkus** [comment]
Fixed via commit 23e56b4

**Comment by Rosethorns** [comment]
Issue not solved. Marble and Limestone deposits are now Big Tile.
